field.formatter.third_party.simple_field_formatter:
  type: mapping
  label: 'Simple Field Formatter entity display settings'
  mapping:
    custom_prefix:
      type: string
      label: Prefix
    custom_suffix:
      type: string
      label: Suffix
    custom_reverse:
      type: boolean
      label: Reverse
    custom_trim:
      type: boolean
      label: Trim
    custom_strtolower:
      type: boolean
      label: strtolower
    custom_strtoupper:
      type: boolean
      label: strtoupper
    custom_ucfirst:
      type: boolean
      label: ucfirst
