<?php

/**
 * @file
 * Contains test_dc.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function test_dc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the test_dc module.
    case 'help.page.test_dc':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Display a message when a user logs in') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function test_dc_theme() {
  $theme = [];
  $theme['test_entity'] = [
    'render element' => 'elements',
    'file' => 'test_entity.page.inc',
    'template' => 'test_entity',
  ];
  $theme['test_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'test_entity.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function test_dc_theme_suggestions_test_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#test_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'test_entity__' . $sanitized_view_mode;
  $suggestions[] = 'test_entity__' . $entity->bundle();
  $suggestions[] = 'test_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'test_entity__' . $entity->id();
  $suggestions[] = 'test_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
